export interface Course {
  id: string
  slug: string
  title: string
  shortDesc: string
  fullDesc: string
  duration: string
  level: "boshlang'ich" | "o'rta" | "yuqori"
  priceFrom: number
  category: "IT" | "Dizayn" | "Til" | "Fan" | "Robotika" | "Marketing"
  age: string
  format: "offline" | "online" | "offline/online"
  startDates: string[]
  program: string[]
  whatYouLearn: string[]
  rating: number
  students: number
  mentor: string
}

export const courses: Course[] = [
  {
    id: "1",
    slug: "suniy-intellekt-ai",
    title: "Sun'iy Intellekt (AI)",
    shortDesc: "Zamonaviy AI texnologiyalari va machine learning asoslari",
    fullDesc:
      "Ushbu kursda siz sun'iy intellekt sohasining asoslarini o'rganasiz. Machine learning, deep learning va neural networks bilan ishlashni o'rganasiz. Python dasturlash tili va AI kutubxonalari bilan amaliy loyihalar ustida ishlaysiz.",
    duration: "3 oy",
    level: "o'rta",
    priceFrom: 1200000,
    category: "IT",
    age: "14+",
    format: "offline/online",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Python dasturlash tili asoslari",
      "Machine Learning kirish",
      "Data Science va ma'lumotlar tahlili",
      "Neural Networks va Deep Learning",
      "Computer Vision asoslari",
      "Natural Language Processing",
      "AI loyihalarini yaratish",
      "Model deployment va production",
    ],
    whatYouLearn: [
      "Python dasturlash tilida ishlash",
      "Machine Learning algoritmlarini qo'llash",
      "Ma'lumotlarni tahlil qilish va vizualizatsiya",
      "Neural networks yaratish va o'qitish",
      "Real AI loyihalarini yaratish",
      "AI modellarini production muhitiga joylashtirish",
    ],
    rating: 4.9,
    students: 45,
    mentor: "Aziz Karimov",
  },
  {
    id: "2",
    slug: "frontend-grafik-dizayn",
    title: "Frontend + Grafik Dizayn",
    shortDesc: "Web dasturlash va zamonaviy dizayn asoslari",
    fullDesc:
      "Frontend dasturlash va grafik dizayn kursida siz zamonaviy veb-saytlar yaratishni o'rganasiz. HTML, CSS, JavaScript va React.js texnologiyalari bilan ishlashni, shuningdek Figma va Adobe Creative Suite dasturlarida dizayn yaratishni o'rganasiz.",
    duration: "4 oy",
    level: "boshlang'ich",
    priceFrom: 900000,
    category: "IT",
    age: "14+",
    format: "offline",
    startDates: ["2024-02-15", "2024-03-15", "2024-04-15"],
    program: [
      "HTML va CSS asoslari",
      "JavaScript dasturlash tili",
      "React.js framework",
      "Responsive web design",
      "Figma dizayn dasturi",
      "Adobe Photoshop va Illustrator",
      "UI/UX dizayn tamoyillari",
      "Portfolio loyihalar yaratish",
    ],
    whatYouLearn: [
      "Zamonaviy veb-saytlar yaratish",
      "Responsive dizayn qilish",
      "JavaScript bilan interaktiv elementlar yaratish",
      "React.js bilan SPA yaratish",
      "Professional dizayn yaratish",
      "UI/UX tamoyillarini qo'llash",
    ],
    rating: 4.8,
    students: 67,
    mentor: "Malika Tosheva",
  },
  {
    id: "3",
    slug: "backend-dasturlash",
    title: "Backend dasturlash",
    shortDesc: "Server tomonidagi dasturlash va ma'lumotlar bazasi",
    fullDesc:
      "Backend dasturlash kursida siz server tomonidagi dasturlashni o'rganasiz. Node.js, Express.js, MongoDB va PostgreSQL bilan ishlashni, API yaratish va ma'lumotlar bazasi bilan ishlashni o'rganasiz.",
    duration: "4 oy",
    level: "boshlang'ich",
    priceFrom: 1000000,
    category: "IT",
    age: "14+",
    format: "offline/online",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Node.js asoslari",
      "Express.js framework",
      "MongoDB ma'lumotlar bazasi",
      "PostgreSQL bilan ishlash",
      "RESTful API yaratish",
      "Authentication va Authorization",
      "Microservices arxitekturasi",
      "Deployment va DevOps asoslari",
    ],
    whatYouLearn: [
      "Server tomonidagi dasturlash",
      "Ma'lumotlar bazasi bilan ishlash",
      "RESTful API yaratish",
      "Xavfsizlik tamoyillarini qo'llash",
      "Scalable backend tizimlar yaratish",
      "Cloud platformalarga deploy qilish",
    ],
    rating: 4.9,
    students: 52,
    mentor: "Sardor Alimov",
  },
  {
    id: "4",
    slug: "kiberxavfsizlik",
    title: "Kiberxavfsizlik",
    shortDesc: "Axborot xavfsizligi va himoya usullari",
    fullDesc:
      "Kiberxavfsizlik kursida siz axborot xavfsizligi sohasining asoslarini o'rganasiz. Ethical hacking, penetration testing, network security va incident response bo'yicha bilim olasiz.",
    duration: "3 oy",
    level: "o'rta",
    priceFrom: 1300000,
    category: "IT",
    age: "16+",
    format: "offline",
    startDates: ["2024-02-15", "2024-03-15", "2024-04-15"],
    program: [
      "Kiberxavfsizlik asoslari",
      "Network Security",
      "Ethical Hacking",
      "Penetration Testing",
      "Malware Analysis",
      "Incident Response",
      "Digital Forensics",
      "Security Compliance",
    ],
    whatYouLearn: [
      "Tizim xavfsizligini ta'minlash",
      "Hujumlarni aniqlash va oldini olish",
      "Penetration testing o'tkazish",
      "Xavfsizlik siyosatlarini ishlab chiqish",
      "Incident response jarayonlari",
      "Digital forensics usullari",
    ],
    rating: 4.9,
    students: 28,
    mentor: "Bobur Karimov",
  },
  {
    id: "5",
    slug: "ingliz-tili",
    title: "Ingliz tili",
    shortDesc: "Amaliy ingliz tili kursi barcha darajalar uchun",
    fullDesc:
      "Ingliz tili kursida siz ingliz tilini noldan o'rganasiz yoki mavjud bilimlaringizni mustahkamlaysiz. Kurs amaliy mashg'ulotlar, suhbat va grammatika darslarini o'z ichiga oladi.",
    duration: "6 oy",
    level: "boshlang'ich",
    priceFrom: 700000,
    category: "Til",
    age: "8+",
    format: "offline",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Ingliz tili alifbosi va talaffuz",
      "Asosiy grammatika qoidalari",
      "Kundalik suhbat",
      "Lug'at boyitish",
      "O'qish va tushunish",
      "Yozish ko'nikmalari",
      "Tinglab tushunish",
      "IELTS/TOEFL tayyorgarlik",
    ],
    whatYouLearn: [
      "Ingliz tilida erkin suhbatlashish",
      "Grammatika qoidalarini qo'llash",
      "Inglizcha matnlarni o'qish va tushunish",
      "Inglizcha yozish ko'nikmalari",
      "Xalqaro imtihonlarga tayyorgarlik",
      "Professional ingliz tili",
    ],
    rating: 4.7,
    students: 89,
    mentor: "John Smith",
  },
  {
    id: "6",
    slug: "xitoy-tili",
    title: "Xitoy tili",
    shortDesc: "Zamonaviy Xitoy tili kursi boshlang'ich darajadan",
    fullDesc:
      "Xitoy tili kursida siz dunyoning eng ko'p so'ralgan tillaridan birini o'rganasiz. Mandarin xitoy tili, HSK imtihoniga tayyorgarlik va xitoy madaniyati bilan tanishish.",
    duration: "6 oy",
    level: "boshlang'ich",
    priceFrom: 700000,
    category: "Til",
    age: "10+",
    format: "offline",
    startDates: ["2024-02-15", "2024-03-15", "2024-04-15"],
    program: [
      "Xitoy tili alifbosi (Pinyin)",
      "Asosiy ieroglif yozuvi",
      "Grammatika asoslari",
      "Kundalik suhbat",
      "Xitoy madaniyati",
      "HSK 1-2 darajasiga tayyorgarlik",
      "Biznes xitoy tili",
      "Xitoy adabiyoti bilan tanishish",
    ],
    whatYouLearn: [
      "Xitoy tilida suhbatlashish",
      "Ieroglif yozuvini o'qish va yozish",
      "Xitoy madaniyatini tushunish",
      "HSK imtihoniga tayyorgarlik",
      "Biznes muloqot ko'nikmalari",
      "Xitoy tilida matn tuzish",
    ],
    rating: 4.5,
    students: 23,
    mentor: "Li Wei",
  },
  {
    id: "7",
    slug: "rus-tili",
    title: "Rus tili",
    shortDesc: "Rus tili kursi boshlang'ich va o'rta darajalar uchun",
    fullDesc:
      "Rus tili kursida siz rus tilini o'rganasiz yoki mavjud bilimlaringizni mustahkamlaysiz. Grammatika, leksika, suhbat va yozish ko'nikmalari rivojlantiriladi.",
    duration: "6 oy",
    level: "boshlang'ich",
    priceFrom: 700000,
    category: "Til",
    age: "8+",
    format: "offline",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Rus tili alifbosi",
      "Grammatika asoslari",
      "Leksika va frazeologiya",
      "Suhbat ko'nikmalari",
      "O'qish va yozish",
      "Rus adabiyoti",
      "Rus madaniyati",
      "TORFL imtihoniga tayyorgarlik",
    ],
    whatYouLearn: [
      "Rus tilida erkin suhbatlashish",
      "Rus tilida o'qish va yozish",
      "Rus grammatikasini qo'llash",
      "Rus madaniyatini tushunish",
      "Professional rus tili",
      "TORFL imtihoniga tayyorgarlik",
    ],
    rating: 4.6,
    students: 34,
    mentor: "Olga Petrova",
  },
  {
    id: "8",
    slug: "matematika",
    title: "Matematika",
    shortDesc: "Maktab va olimpiada matematikasi kursi",
    fullDesc:
      "Matematika kursida o'quvchilar maktab dasturini mustahkamlaydi va olimpiada masalalarini yechishni o'rganadilar. Algebra, geometriya va matematik analiz bo'yicha chuqur bilim oladilar.",
    duration: "6 oy",
    level: "boshlang'ich",
    priceFrom: 800000,
    category: "Fan",
    age: "8+",
    format: "offline",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Algebra asoslari",
      "Geometriya",
      "Trigonometriya",
      "Matematik analiz",
      "Kombinatorika",
      "Ehtimollar nazariyasi",
      "Olimpiada masalalari",
      "DTM tayyorgarlik",
    ],
    whatYouLearn: [
      "Matematik masalalarni yechish",
      "Mantiqiy fikrlash",
      "Olimpiada masalalariga yondashish",
      "DTM imtihoniga tayyorgarlik",
      "Matematik modellashtirish",
      "Analitik fikrlash",
    ],
    rating: 4.8,
    students: 56,
    mentor: "Dilshod Rahimov",
  },
  {
    id: "9",
    slug: "robototexnika",
    title: "Robototexnika",
    shortDesc: "Robotlar yaratish va dasturlash asoslari",
    fullDesc:
      "Robototexnika kursida bolalar va o'smirlar robotlar yaratish, dasturlash va boshqarishni o'rganadilar. Arduino, Raspberry Pi va turli sensorlar bilan ishlash ko'nikmalari rivojlantiriladi.",
    duration: "4 oy",
    level: "boshlang'ich",
    priceFrom: 1100000,
    category: "Robotika",
    age: "10+",
    format: "offline",
    startDates: ["2024-02-15", "2024-03-15", "2024-04-15"],
    program: [
      "Robototexnika asoslari",
      "Arduino bilan ishlash",
      "Sensorlar va aktuatorlar",
      "Robot dasturlash",
      "3D modellashtirish",
      "Robot loyihalar yaratish",
      "Musobaqalarga tayyorgarlik",
      "IoT va aqlli uy tizimlari",
    ],
    whatYouLearn: [
      "Robotlar yaratish va yig'ish",
      "Arduino va Raspberry Pi bilan ishlash",
      "Robot dasturlash",
      "3D modellashtirish va chop etish",
      "Muhandislik fikrlash",
      "Jamoaviy loyihalarda ishlash",
    ],
    rating: 4.8,
    students: 34,
    mentor: "Sardor Alimov",
  },
  {
    id: "10",
    slug: "rassomchilik-dizaynerlik",
    title: "Rassomchilik va Dizaynerlik",
    shortDesc: "Badiiy rassomchilik va grafik dizayn asoslari",
    fullDesc:
      "Rassomchilik va dizaynerlik kursida bolalar badiiy ko'nikmalarini rivojlantiradilar. Rasm chizish, rang nazariyasi, kompozitsiya va zamonaviy dizayn dasturlari bilan ishlashni o'rganadilar.",
    duration: "3 oy",
    level: "boshlang'ich",
    priceFrom: 900000,
    category: "Dizayn",
    age: "7+",
    format: "offline",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Rasm chizish asoslari",
      "Rang nazariyasi",
      "Kompozitsiya qoidalari",
      "Akvarelda rasm chizish",
      "Grafik dizayn asoslari",
      "Adobe Photoshop",
      "Kreativ loyihalar",
      "Portfolio yaratish",
    ],
    whatYouLearn: [
      "Professional rasm chizish",
      "Rang va kompozitsiya qoidalari",
      "Grafik dizayn yaratish",
      "Adobe dasturlari bilan ishlash",
      "Kreativ fikrlash",
      "Badiiy portfolio yaratish",
    ],
    rating: 4.7,
    students: 41,
    mentor: "Nigora Karimova",
  },
  {
    id: "11",
    slug: "smm",
    title: "SMM",
    shortDesc: "Ijtimoiy tarmoqlar marketingi asoslari",
    fullDesc:
      "SMM kursida siz ijtimoiy tarmoqlar orqali marketing qilishni o'rganasiz. Instagram, Facebook, Telegram va boshqa platformalarda kontent yaratish, reklama berish va auditoriya bilan ishlashni o'rganasiz.",
    duration: "2 oy",
    level: "boshlang'ich",
    priceFrom: 900000,
    category: "Marketing",
    age: "14+",
    format: "online",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "SMM asoslari",
      "Kontent strategiya",
      "Instagram marketing",
      "Facebook va Meta Ads",
      "Telegram marketing",
      "Analytics va KPI",
      "Influencer marketing",
      "SMM loyihalar",
    ],
    whatYouLearn: [
      "Ijtimoiy tarmoqlarda marketing",
      "Kontent yaratish va rejalashtirish",
      "Reklama kampaniyalari yaratish",
      "Auditoriya tahlili",
      "SMM strategiya ishlab chiqish",
      "Natijalarni o'lchash va tahlil qilish",
    ],
    rating: 4.6,
    students: 73,
    mentor: "Aziza Tosheva",
  },
  {
    id: "12",
    slug: "smm-ai",
    title: "SMM + AI",
    shortDesc: "Sun'iy intellekt yordamida ijtimoiy tarmoqlar marketingi",
    fullDesc:
      "SMM + AI kursida siz sun'iy intellekt vositalaridan foydalanib, ijtimoiy tarmoqlar marketingini yangi darajaga olib chiqasiz. ChatGPT, Midjourney va boshqa AI vositalar bilan ishlashni o'rganasiz.",
    duration: "2 oy",
    level: "o'rta",
    priceFrom: 1000000,
    category: "Marketing",
    age: "16+",
    format: "online",
    startDates: ["2024-02-15", "2024-03-15", "2024-04-15"],
    program: [
      "AI va SMM integratsiyasi",
      "ChatGPT bilan kontent yaratish",
      "Midjourney bilan vizual kontent",
      "AI analytics vositalari",
      "Avtomatlashtirish",
      "AI chatbotlar yaratish",
      "Personalizatsiya strategiyalari",
      "Kelajak tendentsiyalari",
    ],
    whatYouLearn: [
      "AI vositalar bilan kontent yaratish",
      "SMM jarayonlarini avtomatlashtirish",
      "AI analytics bilan tahlil qilish",
      "Chatbotlar yaratish va sozlash",
      "Personalizatsiya strategiyalari",
      "AI texnologiyalarining kelajagi",
    ],
    rating: 4.9,
    students: 29,
    mentor: "Jasur Karimov",
  },
  {
    id: "13",
    slug: "libos-dizayn",
    title: "Libos dizayn",
    shortDesc: "Moda dizayni va tikuvchilik asoslari",
    fullDesc:
      "Libos dizayn kursida siz moda dizayni va tikuvchilik asoslarini o'rganasiz. Eskiz chizish, naqsh yasash, tikish texnikasi va moda tendentsiyalari bilan tanishasiz.",
    duration: "4 oy",
    level: "boshlang'ich",
    priceFrom: 1000000,
    category: "Dizayn",
    age: "12+",
    format: "offline",
    startDates: ["2024-02-01", "2024-03-01", "2024-04-01"],
    program: [
      "Moda dizayni asoslari",
      "Eskiz chizish texnikasi",
      "Naqsh yasash",
      "Tikish texnikasi",
      "Mato va materiallar",
      "Moda tendentsiyalari",
      "Kolleksiya yaratish",
      "Moda biznes asoslari",
    ],
    whatYouLearn: [
      "Moda eskizlari chizish",
      "Naqsh yasash va o'zgartirish",
      "Professional tikish texnikasi",
      "Moda tendentsiyalarini tahlil qilish",
      "O'z kolleksiyangizni yaratish",
      "Moda biznesini tushunish",
    ],
    rating: 4.5,
    students: 18,
    mentor: "Gulnora Abdullayeva",
  },
  {
    id: "14",
    slug: "modellashtirish",
    title: "Modellashtirish",
    shortDesc: "3D modellashtirish va animatsiya asoslari",
    fullDesc:
      "Modellashtirish kursida siz 3D modellashtirish va animatsiya asoslarini o'rganasiz. Blender, Maya va boshqa dasturlar bilan ishlash, 3D obyektlar yaratish va animatsiya qilishni o'rganasiz.",
    duration: "4 oy",
    level: "boshlang'ich",
    priceFrom: 1000000,
    category: "Dizayn",
    age: "12+",
    format: "offline",
    startDates: ["2024-02-15", "2024-03-15", "2024-04-15"],
    program: [
      "3D modellashtirish asoslari",
      "Blender dasturi bilan ishlash",
      "Modeling texnikalari",
      "Texturing va materiallar",
      "Lighting va rendering",
      "Animatsiya asoslari",
      "VFX effektlar",
      "Portfolio loyihalar",
    ],
    whatYouLearn: [
      "3D obyektlar yaratish",
      "Professional modellashtirish texnikasi",
      "Animatsiya va VFX",
      "Rendering va post-production",
      "Kreativ loyihalar yaratish",
      "3D dizayn portfolio",
    ],
    rating: 4.7,
    students: 25,
    mentor: "Bekzod Rahimov",
  },
]

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug)
}

export function getCoursesByCategory(category: string): Course[] {
  if (category === "all") return courses
  return courses.filter((course) => course.category === category)
}

export function getCoursesByLevel(level: string): Course[] {
  if (level === "all") return courses
  return courses.filter((course) => course.level === level)
}

export function getCoursesByFormat(format: string): Course[] {
  if (format === "all") return courses
  return courses.filter((course) => course.format === format || course.format === "offline/online")
}
